version: "3"

services:
  md5-hashes-api:
    container_name: md5_hashes_api
    build:
      context: ../
      dockerfile: ./deployment/api/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "/tmp:/tmp"
    environment:
      CELERY_BROKER_URL: "amqp://rabbit"
      CELERY_RESULT_BACKEND_URL: "db+postgresql://postgres:postgres@db/postgres"
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      LOGFILE: "/var/log/bostongene_md5"

    depends_on:
      - db
      - rabbit
      - celery-worker

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker:
    build:
      context: ../
      dockerfile: ./deployment/worker/Dockerfile
    volumes:
      - "/tmp:/tmp"
      - "/var/log:/var/log"
    deploy:
      replicas: 3

    environment:
      CELERY_BROKER_URL: "amqp://rabbit"
      CELERY_RESULT_BACKEND_URL: "db+postgresql://postgres:postgres@db/postgres"
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      LOGFILE: "/var/log/bostongene_md5"

    depends_on:
      - db
      - rabbit

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

